fermi_question:
   description: "Generate a fermi question inspired by the relevant content"
   command: 'Generate a fermi question inspired by the following content. Base the question off of well known fermi questions like "How many grains of rice are in a 1kg bag?". Do not make it too philisophical. Do not give the answer or method!'
   generator: combine_with_context
   role: 'system'
   role_content: 'You are a highly creative scientist, engineer, and coder.'
   model: 'gpt-4o-mini'
   temperature: 1.0
   enabled: true
   