services:
  generator:
    build: 
      context: python_generator
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./python_generator/output:/app/output
      - ./python_generator/source:/app/source
      - ./python_generator/config:/app/config
    restart: "no"
  ephemeral_server:
    build:
      context: nodejs_realtime_webapp
      dockerfile: Dockerfile.ephemeral_server
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - generator
    command: ["sh", "-c", "sleep 15 && node ephemeral_server.mjs"] # Replace with health check
    ports:
      - "3000:3000"

  web:
    build:
      context: nodejs_realtime_webapp
      dockerfile: Dockerfile.web
    depends_on:
      - generator
      - ephemeral_server
    volumes:
      - ./python_generator/output:/usr/share/nginx/html/data
    command: ["sh", "-c", "sleep 15 && nginx -g 'daemon off;'"] # Replace with health check
    ports:
      - "8080:80"