pipeline {
    agent any
    triggers {
        githubPush()
    }
    stages {
        stage('Build') {
            steps {
                script {
                    sh """echo $WORKSPACE
                       cd $WORKSPACE/code/python_generator; pwd; ls -alh
                       ./build.sh"""
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    // Get the current host user ID and group ID
                    def uid = sh(script: 'id -u', returnStdout: true).trim()
                    def gid = sh(script: 'id -g', returnStdout: true).trim()

                    // Ensure directories exist and have proper permissions
                    sh """ls -alh \$WORKSPACE \$WORKSPACE/code/python_generator
                        ls -alh \$WORKSPACE/code/python_generator/config
                        ls -alh \$WORKSPACE/code/python_generator/source
                        docker run --rm \\
                            --mount type=bind,src='\$WORKSPACE/code/python_generator/source',dst=/app/source \\
                            --mount type=bind,src='\$WORKSPACE/code/python_generator/generated',dst=/app/output \\
                            --mount type=bind,src='\$WORKSPACE/code/python_generator/config',dst=/app/config \\
                            --user ${uid}:${gid} \\
                            python_generator
                        docker ps
                        ls -alh $WORKSPACE/generated
                        """
                }
            }
        }
    }
    post {
        always {
            script {
                sh 'docker stop python_generator || true'
                sh 'docker rm python_generator || true'
            }
        }
    }
}