pipeline {
    agent any
    triggers {
        githubPush()
    }
    stages {
        stage('Build') {
            steps {
                script {
                    sh """echo $WORKSPACE
                       cd $WORKSPACE/code/python_generator; pwd; ls -alh
                       ./build.sh"""
                }
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'python_generator' // Replace with your specific image
                    args """
                        -v \$WORKSPACE/source:/app/source:ro \
                        -v \$WORKSPACE/generated:/app/output \
                        -v \$WORKSPACE/config:/app/config:ro \
                        -e OPENAI_API_KEY=\$OPENAI_API_KEY \
                        -e YOUTUBE_API_KEY=\$YOUTUBE_API_KEY \
                        --user \$(id -u):\$(id -g)
                    """
                    reuseNode true
                }
            }
        }
    }
    post {
        always {
            script {
                sh 'docker stop python_generator || true'
                sh 'docker rm python_generator || true'
            }
        }
    }
}