FROM nginx:alpine

# Copy static files to the Nginx directory
COPY ./public/ /usr/share/nginx/html

COPY default.conf /etc/nginx/conf.d/default.conf

RUN mkdir /usr/share/nginx/html/data
RUN chmod 777 /usr/share/nginx/html/data
COPY ./output/* /usr/share/nginx/html/data
RUN chmod -R 777 /usr/share/nginx/html/data

# Expose port 80 for the web server
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]