pipeline {
    agent any
    environment {
        OPENAI_API_KEY = credentials('OPENAI_API_KEY')
    }
    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    dir("${env.WORKSPACE}/code/nodejs_realtime_webapp") {
                        sh 'pwd; ls -alh'
                        def image = docker.build("my-node-app:latest", ".")
                    }
                }
            }
        }
        stage('Run Node App in Docker') {
            steps {
                script {
                    dir("${env.WORKSPACE}/code/nodejs_realtime_webapp") {
                        def result = docker.image("my-node-app:latest").inside {
                            sh(script: 'node app.js', returnStatus: true)
                        }
                        if (result != 0) {
                            error "Node app.js failed with exit code ${result}"
                        }
                    }
                }
            }
        }
    }
    post {
        always {
            script {
                sh 'docker rmi my-node-app:latest'
            }
        }
    }
}