fermi_question:
 - description: "Generate a fermi question inspired by the relevant content"
 - command: 'Generate a fermi question inspired by the following content, which will be in the format of """Filename newline content ... repeated"""'
 - generator: combine_with_context
 - enabled: true